/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeSubscription {
  get initialCoverage(): JsCoverage
  stats(): JsStats
  get exclusionGeneration(): bigint
  get rootState(): JsRootState
  replaceExclusions(generation: bigint, prefixes: Array<Buffer>): Promise<JsCoverage>
  reconcile(): Promise<JsReconciliationResult>
  recoverRoot(identityPolicy: string): Promise<JsRootRecoveryResult>
  dispose(): Promise<void>
}

export declare function capabilities(): JsCapabilities

export interface JsCapabilities {
  recursive: boolean
  movedInTreeDiscovery: boolean
  explicitWatchLimits: boolean
  overflowReporting: boolean
  dynamicExclusions: boolean
  reconciliation: boolean
  rootReplacementRecovery: boolean
  exactPathBytes: boolean
}

export interface JsChangeBatch {
  sequence: bigint
  exclusionGeneration: bigint
  rootState: JsRootState
  /**
   * Exact Linux path bytes. The JavaScript wrapper may decode UTF-8 paths,
   * but the native boundary never performs a lossy conversion.
   */
  invalidatedPaths: Array<Buffer>
  coverage: JsCoverage
}

export interface JsCoverage {
  state: string
  reason?: string
  watchedDirectories?: number
  deferredDirectories?: number
}

export interface JsReconciliationResult {
  exclusionGeneration: bigint
  coverage: JsCoverage
}

export interface JsRootIdentity {
  device: bigint
  inode: bigint
}

export interface JsRootRecoveryResult {
  attachment: string
  reason?: string
  previousRootState: JsRootState
  candidateIdentity?: JsRootIdentity
  currentRootState: JsRootState
  exclusionGeneration: bigint
  coverage: JsCoverage
  boundarySequence?: bigint
}

export interface JsRootState {
  generation: bigint
  identity: JsRootIdentity
  attachment: string
  lossEvidence?: string
}

export interface JsStats {
  watchedDirectories: number
  deferredDirectories: number
  rawEvents: bigint
  batchesDelivered: bigint
  batchesDropped: bigint
  topologyScans: bigint
  overflowEvents: bigint
  callbackErrors: bigint
  bridgeDeliveryErrors: bigint
  disposed: boolean
}

export interface JsSubscriptionOptions {
  watchLimit?: number
  batchWindowMs?: number
  maxBatchPaths?: number
  outputQueueCapacity?: number
}

export declare function subscribe(root: string, options: JsSubscriptionOptions | undefined | null, callback: (arg0: JsChangeBatch) => void): Promise<NativeSubscription>
